language: node_js
node_js:
    - "4.2"

before_script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install --quiet -g gulp
    - npm install --quiet -g bower
    - npm install
    - bower install
    - typings install
    - gulp build

script: gulp karma:unit
