language: node_js
node_js:
    - "4.2"

before_script:
    - npm install --quiet -g gulp
    - npm install --quiet -g http-server
    - npm install
    - npm run update-chromedriver
    - bower install
    - npm install --quiet -g bower
    - typings install
    - gulp build

script: gulp karma:unit
