language: node_js
node_js:
    - "4.2"

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install --quiet -g gulp
    - npm install
    - npm run update-chromedriver
    - npm install --quiet -g bower
    - bower install

script: gulp karma:unit
